version: '3.4'

services:

  dev-node:

    container_name: node-dev

    command: ${PROJECT_RUN_CMD}

    build:
      context: ./
      dockerfile: node-dev.Dockerfile
      args:
        VERSION: ${VERSION}
        PROJECT_NAME: ${PROJECT_NAME}

    image: ${REPO}/node-dev:${VERSION}

    ports:
      - "8080:8080"

    volumes:
      - type: bind
        source: ./projects/${PROJECT_NAME}
        target: /usr/src/${PROJECT_NAME}